"""Symbolic regression on the airline satisfaction dataset.

Run with: python research/symbolic_regression.py

Why this exists: the dataset is synthetic, so satisfaction was generated by some
formula over the raw columns. Nine black-box models approximate that formula.
This script tries to recover it directly with genetic programming.

Method:
  1. Subsample 20k rows (gplearn is O(population * rows) per generation).
  2. Evolve 500 formulas for 30 generations with crossover + mutation.
  3. Score every generation's best on AUC.
  4. Validate the winning formula out-of-fold on the full training rows.

The formula is printed, not just the AUC, because the point is to see the
structure the generator used.
"""

from __future__ import annotations

import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import StratifiedKFold

from gplearn.genetic import SymbolicClassifier
from gplearn.functions import make_function

TARGET = "satisfaction"
SEED = 42
SUBSAMPLE = 20_000
POPULATION = 500
GENERATIONS = 30

RAW_COLUMNS = [
    "Age",
    "Flight Distance",
    "Inflight wifi service",
    "Departure/Arrival time convenient",
    "Ease of Online booking",
    "Gate location",
    "Food and drink",
    "Online boarding",
    "Seat comfort",
    "Inflight entertainment",
    "On-board service",
    "Leg room service",
    "Baggage handling",
    "Checkin service",
    "Cleanliness",
    "Departure Delay in Minutes",
    "Arrival Delay in Minutes",
    "Gender",
    "Customer Type",
    "Type of Travel",
    "Class",
]


def _protected_div(x1, x2):
    return np.divide(x1, x2, out=np.zeros_like(x1), where=x2 != 0)


def _protected_sqrt(x1):
    return np.sqrt(np.abs(x1))


def _protected_log(x1):
    return np.log(np.abs(x1) + 1e-6)


def build_features(frame: pd.DataFrame) -> pd.DataFrame:
    """Encode categoricals as integers and fill missing delays."""
    out = frame.copy()
    for col in ["Gender", "Customer Type", "Type of Travel", "Class"]:
        out[col] = pd.Categorical(out[col]).codes
    out["Arrival Delay in Minutes"] = out["Arrival Delay in Minutes"].fillna(0)
    out["Departure Delay in Minutes"] = out["Departure Delay in Minutes"].fillna(0)
    return out[RAW_COLUMNS].astype(np.float64)


def main() -> None:
    print("=" * 80, flush=True)
    print("SYMBOLIC REGRESSION - recovering the generator's formula", flush=True)
    print("=" * 80, flush=True)

    df = pd.read_csv("data/train.csv")
    df = df.sample(n=SUBSAMPLE, random_state=SEED).reset_index(drop=True)
    X = build_features(df)
    y = df[TARGET].astype(int).to_numpy()

    div = make_function(function=_protected_div, name="pdiv", arity=2)
    sqrt = make_function(function=_protected_sqrt, name="psqrt", arity=1)
    log = make_function(function=_protected_log, name="plog", arity=1)

    function_set = ["add", "sub", "mul", "div", "sin", "cos", "sqrt", "log", "neg", "abs"]

    est = SymbolicClassifier(
        population_size=POPULATION,
        generations=GENERATIONS,
        tournament_size=20,
        stopping_criteria=0.96,
        p_crossover=0.7,
        p_subtree_mutation=0.1,
        p_hoist_mutation=0.05,
        p_point_mutation=0.1,
        max_samples=0.9,
        parsimony_coefficient=0.001,
        function_set=function_set,
        random_state=SEED,
        verbose=1,
        n_jobs=1,
    )

    started = time.monotonic()
    est.fit(X.to_numpy(), y)
    elapsed = time.monotonic() - started

    formula = str(est._program)
    train_pred = est.predict_proba(X.to_numpy())[:, 1]
    train_auc = roc_auc_score(y, train_pred)

    print(flush=True)
    print("=" * 80, flush=True)
    print("RESULT", flush=True)
    print("=" * 80, flush=True)
    print(f"Formula:    {formula}", flush=True)
    print(f"Train AUC:  {train_auc:.6f}  (on {SUBSAMPLE:,} subsample rows)", flush=True)
    print(f"Time:       {elapsed:.1f}s", flush=True)

    print(flush=True)
    print("Validating out-of-fold on full training rows...", flush=True)
    full = pd.read_csv("data/train.csv")
    X_full = build_features(full).to_numpy()
    y_full = full[TARGET].astype(int).to_numpy()

    oof = np.zeros(len(y_full))
    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)
    for fold, (fit_idx, val_idx) in enumerate(skf.split(X_full, y_full)):
        est_fold = SymbolicClassifier(
            population_size=POPULATION,
            generations=GENERATIONS,
            tournament_size=20,
        stopping_criteria=0.0,
            p_crossover=0.7,
            p_subtree_mutation=0.1,
            p_hoist_mutation=0.05,
            p_point_mutation=0.1,
            max_samples=0.9,
            parsimony_coefficient=0.001,
            function_set=function_set,
            random_state=SEED + fold,
            verbose=0,
            n_jobs=1,
        )
        est_fold.fit(X_full[fit_idx], y_full[fit_idx])
        oof[val_idx] = est_fold.predict_proba(X_full[val_idx])[:, 1]
        fold_auc = roc_auc_score(y_full[val_idx], oof[val_idx])
        print(f"  fold {fold + 1}: AUC = {fold_auc:.6f}", flush=True)

    oof_auc = roc_auc_score(y_full, oof)
    print(f"OOF AUC:    {oof_auc:.6f}  (on {len(y_full):,} full rows)", flush=True)
    print(flush=True)
    print("If OOF AUC > 0.96, the formula captures real structure.", flush=True)
    print("If OOF AUC << train AUC, the formula overfit the subsample.", flush=True)


if __name__ == "__main__":
    main()
